//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUXUAT
    {
        public int Ma_PhieuXuat { get; set; }
        public int Ma_MatHang { get; set; }
        public int So_Luong { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
    }
}
