//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class CHITIETPHIEUNHAP
    {
        public int Ma_PhieuNhap { get; set; }
        public int Ma_MatHang { get; set; }
        public int So_Luong { get; set; }

        public CHITIETPHIEUNHAP(DataRow row)
        {
            this.Ma_PhieuNhap = (int)row["Ma_PhieuNhap"];
            this.Ma_MatHang = (int)row["Ma_MatHang"];
            this.So_Luong = (int)row["So_Luong"];
        }

        public virtual MATHANG MATHANG { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
