//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class CHUCVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUCVU()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
        public CHUCVU(DataRow row)
        {
            this.Ma_Chuc_Vu = (int)row["Ma_Chuc_Vu"];
            this.Ten_Chuc_Vu = row["Ten_Chuc_Vu"].ToString();
        }


        public int Ma_Chuc_Vu { get; set; }
        public string Ten_Chuc_Vu { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
