//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class DONVI
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONVI(string Loai_Dvi)
        {
            this.Loai_Dvi = Loai_Dvi;
        }

        public DONVI(DataRow row)
        {
            this.Ma_Dvi = (int)row["Ma_Dvi"];
            this.Loai_Dvi = row["Loai_Dvi"].ToString();
        }

        public int Ma_Dvi { get; set; }
        public string Loai_Dvi { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<MATHANG> MATHANGs { get; set; }
    }
}
