//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;
    using System.Data;

    public class NHACUNGCAP : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHACUNGCAP()
        {
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
        }
        public NHACUNGCAP(DataRow row)
        {
            this.Ma_NCC = (int)row["Ma_NCC"];
            this.Ten_NCC = row["Ten_NCC"].ToString();
            this.Dia_Chi = row["Dia_Chi"].ToString();
            this.Dienthoai = row["Dienthoai"].ToString();
            this.email = row["email"].ToString();
            this.Ngayki_hd = (DateTime)row["Ngayki_hd"];


        }
        public int Ma_NCC { get; set; }
        public string Ten_NCC { get; set; }
        public string Dia_Chi { get; set; }
        public string Dienthoai { get; set; }
        public string email { get; set; }
        public DateTime Ngayki_hd { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
    }
}
