//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class NHANVIEN : ViewModel.BaseViewModel
    {
       /* [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]*/
       /* public NHANVIEN()
        {
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
            this.PHIEUXUATs = new HashSet<PHIEUXUAT>();
        }*/
        public NHANVIEN(int Ma_Chuc_Vu, string Ten_NV, DateTime Ngay_Sinh, string Dia_Chi, string Ten_DN, string MK)
        {
            this.Ma_CV = Ma_Chuc_Vu;
            this.Ten_NV = Ten_NV;
            this.Ngay_Sinh = Ngay_Sinh;
            this.Dia_Chi = Dia_Chi;
            this.Ten_DN = Ten_DN;
            this.MK = MK;
        }

        public NHANVIEN(int Ma_NV, CHUCVU cv, string Ten_NV, DateTime Ngay_Sinh, string Dia_Chi, string Ten_DN, string MK)
        {
            this.Ma_NV = Ma_NV;
            this.CHUCVU = cv;
            this.Ten_NV = Ten_NV;
            this.Ngay_Sinh = Ngay_Sinh;
            this.Dia_Chi = Dia_Chi;
            this.Ten_DN = Ten_DN;
            this.MK = MK;
        }

        public NHANVIEN(DataRow row)
        {
            this.Ma_NV = (int)row["Ma_NV"];
            this.Ma_CV = (int)row["Ma_Chuc_Vu"];
            this.Ten_NV = row["Ten_NV"].ToString();
            this.Ngay_Sinh = (DateTime)row["Ngay_Sinh"];
            this.Dia_Chi = row["Dia_Chi"].ToString();
            this.Ten_DN = row["Ten_DN"].ToString();
            this.MK = row["MK"].ToString();
        }

        private string _Ten_DN;
        public string Ten_DN { get => _Ten_DN; set { _Ten_DN = value; OnPropertyChanged(); } }

        private string _Ten_NV;
        public string Ten_NV { get => _Ten_NV; set { _Ten_NV = value; OnPropertyChanged(); } }

        private DateTime _Ngay_Sinh;
        public DateTime Ngay_Sinh { get => _Ngay_Sinh; set { _Ngay_Sinh = value; OnPropertyChanged(); } }

        private string _Dia_Chi;
        public string Dia_Chi { get => _Dia_Chi; set { _Dia_Chi = value; OnPropertyChanged(); } }

        private string _MK;
        public string MK { get => _MK; set { _MK = value; OnPropertyChanged(); } }

        private int _Ma_NV;
        public int Ma_NV { get => _Ma_NV; set { _Ma_NV = value; OnPropertyChanged(); } }

        private int _Ma_CV;
        public int Ma_CV { get => _Ma_CV; set { _Ma_CV = value; OnPropertyChanged(); } }

        private CHUCVU _CHUCVU;
        public virtual CHUCVU CHUCVU { get => _CHUCVU; set { _CHUCVU = value; OnPropertyChanged(); } }
        /* [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]*/
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
    /*    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]*/
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs { get; set; }
    }
}
